# ----- development
#   name: test-repo
backend:
  name: git-gateway
  branch: feature/netlifycms
  commit_messages:
    create: 'Create {{collection}} “{{slug}}” ✨'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
show_preview_links: true
site_url: "https://netlify-with-gatsby4blog.netlify.app"
display_url: "https://netlify-with-gatsby4blog.netlify.app"

# Wehere it create images
media_folder: "/static/images/blog"
# where use the images
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/data/blog"
    create: true
    widget: "object"
    #slug for markdown filename 
    slug: "{{slug}}.{{fields.lang}}"
    editor:
      preview: true
    fields:
      - { label: "Author", name: "author", widget: "select", options: ["4GeeksAcademy", "MRiciglianoC", "alesanchezr"]}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string"}
      - { label: "Link", name: "link", widget: "string", required: false}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image"}
      # Slug for frontmatter path
      - { label: "Slug", name: slug, widget: string, required: true, pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'The slug can have no spaces or special characters']}
      - { label: "Lang", name: "lang", widget: "select", options: ['us', 'es'] }
      - { label: "Status", name: "status", widget: "hidden", default: "published"}
      - { label: "Featured", name: "featured", widget: "boolean", default: false}
      - { label: "Categories", name: "categories", widget: "list"}
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
